[package]
name = "rlogger"
version = "0.1.0"
authors = ["Hideo Hattori <hattori-h@klab.com>"]

[dependencies]
time = "0.1"
byteorder = "0.5"

[dev-dependencies]
tempdir = "0.3"

[[bench]]
name = "bench"
path = "src/bench.rs"
